name: CD

on:
  push:
    paths:
      - 'CHANGELOG.md'

env:
  NODE_VERSION: '16'

jobs:
  check-version:
    name: 'Check Deployable'
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
      type: ${{ steps.check.outputs.type }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version Check
        id: check
        uses: EndBug/version-check@v2.1.0

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: [check-version]

    if: needs.check-version.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Node Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.NODE_VERSION }}-${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
